import { Construct } from 'constructs';
import { RemovalPolicy, Tags } from 'aws-cdk-lib';
import * as bedrockagentcore from 'aws-cdk-lib/aws-bedrockagentcore';

export interface AgentCoreMemoryProps {
  /**
   * Memory name prefix
   */
  namePrefix: string;

  /**
   * Environment name (dev, prod, etc.)
   */
  envName: string;

  /**
   * Event expiry duration in days
   * @default 90
   */
  eventExpiryDuration?: number;

  /**
   * Description of the memory resource
   */
  description?: string;

  /**
   * Whether to enable summary memory strategy
   * @default true
   */
  enableSummaryStrategy?: boolean;

  /**
   * Whether to enable semantic memory strategy
   * @default true
   */
  enableSemanticStrategy?: boolean;

  /**
   * Removal policy for the memory resource
   * @default RemovalPolicy.DESTROY
   */
  removalPolicy?: RemovalPolicy;
}

export class AgentCoreMemory extends Construct {
  public readonly memory: bedrockagentcore.CfnMemory;
  public readonly memoryId: string;
  public readonly summaryStrategyId?: string;
  public readonly semanticStrategyId?: string;

  constructor(scope: Construct, id: string, props: AgentCoreMemoryProps) {
    super(scope, id);

    const {
      namePrefix,
      envName,
      eventExpiryDuration = 90,
      description,
      enableSummaryStrategy = true,
      enableSemanticStrategy = true,
      removalPolicy = RemovalPolicy.DESTROY,
    } = props;

    // Memory name (must start with letter, alphanumeric and underscores only)
    const memoryName = `${namePrefix}_${envName}_memory`.replace(/-/g, '_');

    // Build memory strategies
    const memoryStrategies: bedrockagentcore.CfnMemory.MemoryStrategyProperty[] = [];

    if (enableSummaryStrategy) {
      memoryStrategies.push({
        summaryMemoryStrategy: {
          name: 'Summary',
          description: 'Summarizes conversation history for persona long-term memory',
        },
      });
    }

    if (enableSemanticStrategy) {
      memoryStrategies.push({
        semanticMemoryStrategy: {
          name: 'Semantic',
          description: 'Stores factual and knowledge information for semantic search',
        },
      });
    }

    // Create AgentCore Memory
    this.memory = new bedrockagentcore.CfnMemory(this, 'Default', {
      name: memoryName,
      eventExpiryDuration,
      description: description || `AgentCore Memory for AI Persona ${envName} environment`,
      memoryStrategies: memoryStrategies.length > 0 ? memoryStrategies : undefined,
    });

    this.memory.applyRemovalPolicy(removalPolicy);

    // Add tags
    Tags.of(this.memory).add('Environment', envName);
    Tags.of(this.memory).add('Application', 'AIPersona');

    // Export memory ID
    this.memoryId = this.memory.attrMemoryId;

    // Get strategy IDs if enabled
    // Note: Strategy IDs are generated by the service, we'll need to reference them via the memory
    if (enableSummaryStrategy) {
      // The strategy ID will be available after deployment
      // For now, we'll use a placeholder that can be resolved
      this.summaryStrategyId = 'Summary';
    }

    if (enableSemanticStrategy) {
      // The strategy ID will be available after deployment
      this.semanticStrategyId = 'Semantic';
    }
  }
}
